account/urls.py
from django.urls import path, include

# Классы обработчики аутентификации Django
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    # Определённые ранее обработчики
    # path('login/', views.user_login, name='login'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # # Шаблоны для доступа к обработчикам смены пароля.
    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # # Шаблоны востановления пороля
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', views.dashboard, name='dashboard'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

# PaasswordResetView – обработчик восстановления пароля. Он генерирует временную
# ссылку с токеном и отправляет ее на  электронную почту пользователя;
# PasswordResetDoneView – отображает страницу с сообщением о том, что ссылка
# восстановления пароля была отправлена на электронную почту;
# PasswordResetConfirmView – позволяет пользователю указать новый пароль;
# PasswordResetCompleteView – отображает сообщение об успешной смене пароля.

bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('jquery/', include('jquery.urls', namespace='jquery')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views


app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

account/models.py
from django.contrib.auth.models import User
from django.db import models

from django.conf import settings

class Profile(models.Model):
    # Чтобы наш код не зависел от конкретной модели пользователя, мы используем функцию get_user_model().
    # Она возвращает модель, указанную в настройке AUTH_USER_MODEL, и мы можем легко заменять класс пользователя,
    # т. к. не обращались в коде напрямую к конкретной модели.
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d', blank=True)

    def __str__(self):
        return f"Profile for user {self.user.username}"


# В предыдущей главе мы добавили отношение «многие ко многим» с помощью
# поля модели ManyToManyField, и Django создал для него таблицу. Это подходит
# для большинства случаев, но иногда необходимо явно задать промежуточную
# модель. Например, это может быть полезно, когда необходимо сохранить до-
# полнительную информацию об отношении (например, когда оно было созда-
# но) или некоторые поля, поясняющие суть отношения.
# Мы добавим такую промежуточную модель. Есть две причины, объясняю-
# щие необходимость этого в нашем проекте:
# мы используем стандартную модель пользователя User из Django и не мо-
# жем ее модифицировать;
# мы хотим сохранить время создания отношения.


class Contact(models.Model):
    # ForeignKey на пользователя подписчика
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    # ForeignKey на пользователя, на которого подписались
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f"{self.user_form} follows {self.user_to}"

# Здесь мы обращаемся к методу модели add_to_class(), чтобы с легкостью
# изменить ее. Стоит отметить, что такой способ добавления атрибута реко-
# мендуется использовать только в особенных случаях. Здесь это оправданно,
# т. к. мы:
# упростили доступ к связанным объектам c помощью Django ORM – user.
# followers.all() и user.following.all(). Добавили промежуточную модель
# Contact и избежали лишних объединений таблиц в базе данных, как это
# было бы, если бы мы определили связь в модели Profile;
#  создали таблицу для связи из модели Contact. Таким образом, динамиче-
# ски добавленное в модель User поле ManyToManyField никак не повлияет на
# таблицу пользователей;
#  избежали создания собственной модели пользователя, оставив стан-
# дартную модель User и все ее возможности

User.add_to_class('following',
                  models.ManyToManyField('self', through=Contact,
                                         related_name='followers',
                                         symmetrical=False))

account/forms.py
from django import forms

from django.contrib.auth.models import User
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrstionForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password don\'t match.')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User

from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from django.http import JsonResponse
from .models import Contact

from django.contrib.auth import authenticate, login

from .forms import LoginForm, UserRegistrstionForm, UserEditForm, ProfileEditForm

from .models import Profile

from django.contrib import messages


def user_login(request):
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # сверяем с данными в базе с помощью функции authenticate(). Она принимает аргументы request, username
            # и passwordи возвращает объект пользователя User, если он успешно аутентифицирован.В противном случае
            # вернется None. Если пользователь не был аутентифицирован, возвращаем объект HttpResponse с сообщением
            # о некорректном логине или пароле
            user = authenticate(request, username=cd['username'], password=cd['password'])
            # Если юзер существует
            if user is not None:
                # если пользователь был аутентифицирован, проверяем, активен ли он, через атрибут модели пользователя
                # Django, is_active (не заблокирован). Если пользователь неактивный, возвращаем HttpResponse
                # с соответствующим сообщением;
                if user.is_active:
                    # если пользователь активный, авторизуем его на сайте. Это происходит
                    # посредством вызова функции login(), которая запоминает пользователя
                    # в сессии. Затем возвращаем HttpResponse с сообщением об успешной авторизации.
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    # Наш обработчик обернут в декоратор login_required. Он проверяет, авторизован ли пользователь. Если пользователь
    # авторизован, Django выполняет обработку. В противном случае пользователь перенаправляется на страницу логина.
    # При этом в GET-параметре задается next -адрес запрашиваемой страницы. Таким образом, после успешного прохождения
    # авторизации пользователь будет перенаправлен на страницу, куда он пытался попасть.

    # Также мы добавили переменную контекста section, с помощью которой смо-
    # жем узнать, какой раздел сайта сейчас просматривает пользователь.
    return render(request, 'account/dashboard.html', {'section': 'dashboard'})


def register(request):
    if request.POST:
        user_form = UserRegistrstionForm(request.POST)
        if user_form.is_valid():
            # Создаём нового пользователя, но пока не сохраняем в базу данных.
            new_user = user_form.save(commit=False)
            # Задаём пользователю зашифрованный пароль.
            new_user.set_password(user_form.cleaned_data['password'])

            # Создание профиля пользователя.
            Profile.objects.create(user=new_user)

            # Сохраняем пользователя в базе данных.
            new_user.save()
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrstionForm()
    return render(request, 'account/register.html', {'user_form': user_form})

# Мы обернули функцию в декоратор login_required, потому что для измене-
# ния профиля пользователь должен быть авторизован.
@login_required
def edit(request):
    if request.POST:
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})

def privacy_policy(request):
    return render(request, 'account/privacy_policy.html')


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'account/user/list.html',
                  {'section': 'people', 'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'account/user/detail.html',
                  {'section': 'people', 'user': user})

@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'ok'})

account/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
  <div id="header">
    <span class="logo">Bookmarks</span>

<!--    следует определить, выполнил ли текущий пользователь вход в свой аккаунт или он является анонимным. Текущий
пользователь задается в объекте HttpRequest промежуточным слоем. Мы можем в любой момент обратиться к нему через
request.user и получим объект типа User. Неавторизованный пользователь является объектом типа AnonymousUser.
Чтобы определить, с каким типом пользователя мы имеем дело, достаточно обратиться к атрибуту is_authenticated.-->
    {% if request.user.is_authenticated %}
      <ul class="menu">
        <li {% if section == "dashboard" %} class="selected" {% endif %}>
          <a href="{% url 'dashboard' %}">My dashboard</a>
        </li>
        <li {% if section == "images" %} class="selected" {% endif %}>
          <a href="{% url 'images:list' %}">Images</a>
        </li>
        <li {% if section == "people" %} class="selected" {% endif %}>
          <a href="{% url 'user_list' %}">People</a>
        </li>
      </ul>
    {% endif %}
    <span class="user">
      {% if request.user.is_authenticated %}
        Hello {{ request.user.first_name }},
        <a href="{% url 'logout' %}">Log-out</a>
      {% else %}
        <a href="{% url 'login' %}">Log-in</a>
      {% endif %}
    </span>
  </div>

<!-- from django.contrib import messages
messages.error(request, 'Something went wrong')
 Мы можем создать уведомление с помощью функции add_message() или лю-
бой из перечисленных ниже:
 success()– сообщение об успешном завершении действия;
 info()– информационное сообщение;
 warning() – что-то пошло не так, но пока ошибка не критична;
 error()– действие не завершилось или произошла ошибка;
 debug() – отладочное сообщение, которое не будет отображаться в боевом
окружении.-->
  {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
          <a href="#" class="close">x</a>
        </li>
      {% endfor %}
  {% endif %}
    </ul>

  <div id="content">
    {% block content %} {% endblock %}
  </div>

<!--Мы подключили библиотеку jQuery из CDN Google. Есть второй способ ее
подключения: скачать jQuery с сайта https://jquery.com/ в папку static и под-
ключить код оттуда.
Мы добавили тег <script> для использования JavaScript-кода. Метод $(document).
ready() – это функция jQuery, она получает в качестве аргумента код,
который будет выполнен, когда удастся выстроить иерархию документа (Document
Object Model – DOM). Браузер формирует DOM в виде древовидной струк-
туры после загрузки страницы. Передавая выполняемый код в метод ready(),
гарантируем, что элементы, с которыми мы будем взаимодействовать, будут
загружены и доступны в DOM (наш код выполнится только после того, как бра-
узер сформирует его).
Внутри обработчика мы добавили блочный тег Django и назвали его domready.
Так дочерние шаблоны смогут добавлять собственный JavaScript-код, который
должен выполняться после формирования DOM.-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<!--          для AJAX-запросов обычно не используют добавление CSRF-токена в данные
каждого запроса. Вместо этого Django позволяет нам указать собственный за-
головок X-CSRFToken со значением токена. Таким образом, при использовании
jQuery или любой другой JavaScript-библиотеки для асинхронных запросов за
головок X-CSRFToken будет содержать токен, вследствие чего Django сможет об-
работать этот запрос.
Для того чтобы добавить токен в каждый асинхронный запрос, необходимо:
1) получить CSRF-токен из csrftoken (задается, когда защита от CSRF акти-
вирована в настройках проекта);
2) отправить токен в заголовке X-CSRFToken.
Более подробно о CSRF-защите при AJAX-запросах можно прочитать на
странице https:// docs.djangoproject.com/en/2.0/ref/csrf/#ajax

Новый код выполняет следующие действия:
1) подключает плагин JSCookie из публичного CDN. JSCookie – это библио-
тека, облегчающая работу с куками. Познакомиться с ней можно на сайте
https://github.com/js-cookie/js-cookie;
2) получает значение csrftoken с помощью Cookies.get();
3) добавляет функцию csrfSafeMethod(), которая определяет, нужно ли про-
верять CSRF-токен для текущего HTTP-метода. Методы, которые не тре-
буют проверки, – GET, HEAD, OPTIONS, TRACE;
4) настраивает AJAX-запросы методом $.ajaxSetup(). Перед отправкой каж-
дого AJAX-запроса проверяет, нужно ли выставлять CSRF-токен. Если
нужно, то задает в заголовке X-CSRFToken запроса значение токена, полу-
ченное из куков.
В нашем случае CSRF-токен будет добавляться в заголовки запросов мето-
дами POST и PUT.--->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script
  src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script>
      var csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
          // Для этих методов токен не будет подставляться в заголовок.
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
      $(document).ready(function(){
       {% block domready %}
          {% endblock %}
      });
  </script>
</body>
</html>