bookmarks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('jquery/', include('jquery.urls', namespace='jquery')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views


app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
]

jquery/urls.py
from django.urls import path

from jquery import views

app_name = 'jquery'

urlpatterns = [
    path('table/', views.table, name='table'),
    path('board/', views.board, name='board'),
    path('simple_disappear/', views.simple_disappear, name='simple_disappear'),
    path('chainable_effects/', views.chainable_effects, name='chainable_effects'),
    path('accordion1/', views.accordion1, name='accordion'),
    path('accordion2/', views.accordion2, name='accordion2'),
    path('animated_hover/', views.animated_hover, name='animated_hover'),
    path('animated_hover2/', views.animated_hover2, name='animated_hover2'),
    path('block_clickable/', views.block_clickable, name='block_clickable'),
    path('collapsible_panels/', views.collapsible_panels, name='collapsible_panel'),
    path('illustrations/', views.illustrations, name='illustrations'),
]

jquery/models.py
from django.db import models

# Create your models here.

jquery/views.py
from django.shortcuts import render

def board(request):
    return render(request, 'jquery/board.html')

def simple_disappear(request):
    return render(request, 'jquery/simple_disappear.html')

def chainable_effects(request):
    return render(request, 'jquery/chainable_effects.html')

def accordion1(request):
    return render(request, 'jquery/accordion1.html')

def accordion2(request):
    return render(request, 'jquery/accordion2.html')

def animated_hover(request):
    return render(request, 'jquery/animated_hover.html')

def animated_hover2(request):
    return render(request, 'jquery/animated_hover2.html')

def block_clickable(request):
    return render(request, 'jquery/block_clickable.html')

def collapsible_panels(request):
    return render(request, 'jquery/collapsible_panels.html')

def illustrations(request):
    return render(request, 'jquery/illustrations.html')

def table(request):
    return render(request, 'jquery/table.html')

jquery/templates/jquery/accordion1.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Accordion 1</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(function () {

      $(".accordion h3:first").addClass("active");
      $(".accordion p:not(:first)").hide();

      $(".accordion h3").click(function () {
        $(this).next("p").slideToggle("slow")
          .siblings("p:visible").slideUp("slow");
        $(this).toggleClass("active");
        $(this).siblings("h3").removeClass("active");
      });

    });
  </script>

  <style type="text/css">
    body {
      margin: 10px auto;
      width: 570px;
      font: 75%/120% Arial, Helvetica, sans-serif;
    }

    .accordion {
      width: 480px;
      border-bottom: solid 1px #c4c4c4;
    }

    .accordion h3 {
      background: #e9e7e7 url(../../static/images/arrow-square.gif) no-repeat right -51px;
      padding: 10px 15px;
      margin: 0;
      font: bold 120%/100% Arial, Helvetica, sans-serif;
      border: solid 1px #c4c4c4;
      border-bottom: none;
      cursor: pointer;
    }

    .accordion h3:hover {
      background-color: #e3e2e2;
    }

    .accordion h3.active {
      background-position: right 5px;
    }

    .accordion p {
      background: #f7f7f7;
      margin: 0;
      padding: 10px 15px 20px;
      border-left: solid 1px #c4c4c4;
      border-right: solid 1px #c4c4c4;
    }

    @media screen and (max-width: 480px) {
      body {
        width: 100%;
        margin: 0;
        padding: 0;
      }

      .accordion {
        width: 98%;
        margin: 1%;
      }

      .accordion h3 {
        padding: 12px 15px;
      }

      .goog-zippy-expanded {
        background: #e9e7e7 url(../../static/images/arrow-square.gif) no-repeat right 10px;
      }

      .goog-zippy-collapsed {
        background: #e9e7e7 url(../../static/images/arrow-square.gif) no-repeat right -46px;
      }
    }
  </style>
</head>

<body>

<div class="accordion">
  <h3>Question One Sample Text</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>This is Question Two</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>Another Questio here</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>Sample heading</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>Sample Question Heading</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
</div>

</body>
</html>

jquery/templates/jquery/accordion2.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Accordion 2</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(function () {

      $(".accordion2 h3").eq(2).addClass("active");
      $(".accordion2 p").eq(2).show();

      $(".accordion2 h3").click(function () {
        $(this).next("p").slideToggle("slow")
          .siblings("p:visible").slideUp("slow");
        $(this).toggleClass("active");
        $(this).siblings("h3").removeClass("active");
      });

    });
  </script>

  <style type="text/css">
    body {
      margin: 10px auto;
      width: 570px;
      font: 75%/120% Arial, Helvetica, sans-serif;
    }

    .accordion2 {
      width: 480px;
      border-bottom: solid 1px #c4c4c4;
    }

    .accordion2 h3 {
      background: #e9e7e7 url(../../static/images/arrow-square.gif) no-repeat right -51px;
      padding: 7px 15px;
      margin: 0;
      font: bold 120%/100% Arial, Helvetica, sans-serif;
      border: solid 1px #c4c4c4;
      border-bottom: none;
      cursor: pointer;
    }

    .accordion2 h3:hover {
      background-color: #e3e2e2;
    }

    .accordion2 h3.active {
      background-position: right 5px;
    }

    .accordion2 p {
      background: #f7f7f7;
      margin: 0;
      padding: 10px 15px 20px;
      border-left: solid 1px #c4c4c4;
      border-right: solid 1px #c4c4c4;
      display: none;
    }

    @media screen and (max-width: 480px) {
      body {
        width: 100%;
        margin: 0;
        padding: 0;
      }

      .accordion {
        width: 98%;
        margin: 1%;
      }

      .accordion h3 {
        padding: 12px 15px;
      }

      .goog-zippy-expanded {
        background: #e9e7e7 url(../../static/images/arrow-square.gif) no-repeat right 10px;
      }

      .goog-zippy-collapsed {
        background: #e9e7e7 url(../../static/images/arrow-square.gif) no-repeat right -46px;
      }
    }
  </style>
</head>

<body>

<div class="accordion2">
  <h3>Question One Sample Text</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>This is Question Two</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>Another Questio here</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>Sample heading</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
  <h3>Sample Question Heading</h3>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi malesuada, ante at feugiat tincidunt, enim massa
    gravida metus, commodo lacinia massa diam vel eros. Proin eget urna. Nunc fringilla neque vitae odio. Vivamus vitae
    ligula.</p>
</div>

</body>
</html>

jquery/templates/jquery/animated_hover.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Animated Menu Hover 1</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(function () {

      $(".menu a").hover(function () {
        $(this).next("em").stop(true, true)
          .animate({opacity: "show", top: "-75"}, "slow");
      }, function () {
        $(this).next("em").stop(true, true)
          .animate({opacity: "hide", top: "-100"}, "fast");
      });


    });
  </script>

  <style type="text/css">
    body {
      margin: 10px auto;
      width: 570px;
      font: 75%/120% Arial, Helvetica, sans-serif;
    }

    .menu {
      margin: 100px 0 0;
      padding: 0;
      list-style: none;
    }

    .menu li {
      padding: 0;
      margin: 0 2px;
      float: left;
      position: relative;
      text-align: center;
    }

    .menu a {
      padding: 14px 10px;
      display: block;
      color: #000000;
      width: 144px;
      text-decoration: none;
      font-weight: bold;
      background: url(../../static/images/button.gif) no-repeat center center;
    }

    .menu li em {
      background: url(../../static/images/hover.png) no-repeat;
      width: 180px;
      height: 45px;
      position: absolute;
      top: -75px;
      left: -15px;
      text-align: center;
      padding: 20px 12px 10px;
      font-style: normal;
      z-index: 2;
      display: none;
      color: #0ac33e;
    }
  </style>
</head>

<body>

<ul class="menu">
  <li>
    <a href="http://www.webdesignerwall.com">Web Designer Wall</a>
    <em>A wall of design ideas, web trends, and tutorials</em>
  </li>
  <li>
    <a href="http://bestwebgallery.com">Best Web Gallery</a>
    <em>Featuring the best CSS and Flash web sites</em>
  </li>
  <li>
    <a href="http://www.ndesign-studio.com">N.Design Studio</a>
    <em>Blog and design portfolio of WDW designer, Nick La</em>
  </li>
</ul>

</body>
</html>

jquery/templates/jquery/animated_hover2.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Animated Menu Hover 2</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(function () {
      $(".menu2 a").append("<em></em>");
      $(".menu2 a").hover(function () {
        $(this).find("em").stop(true, true).animate({opacity: "show", top: "-75"}, "slow");
        var hoverText = $(this).attr("title");
        $(this).find("em").text(hoverText);
      }, function () {
        $(this).find("em").stop(true, true).animate({opacity: "hide", top: "-85"}, "fast");
      });


    });
  </script>
  <style type="text/css">
    body {
      margin: 10px auto;
      width: 570px;
      font: 80%/120% Arial, Helvetica, sans-serif;
    }

    .menu2 {
      margin: 100px 0 0;
      padding: 0;
      list-style: none;
    }

    .menu2 li {
      padding: 0;
      margin: 0 2px;
      float: left;
      position: relative;
      text-align: center;
    }

    .menu2 a {
      padding: 14px 10px;
      display: block;
      color: #000000;
      width: 144px;
      text-decoration: none;
      font-weight: bold;
      background: url(../../static/images/button.gif) no-repeat center center;
    }

    .menu2 li em {
      font-weight: normal;
      background: url(../../static/images/hover.png) no-repeat;
      width: 180px;
      height: 45px;
      position: absolute;
      top: -85px;
      left: -15px;
      text-align: center;
      padding: 20px 12px 10px;
      font-style: normal;
      z-index: 2;
      display: none;
      color: #00cffa;
    }
  </style>
</head>

<body>
<ul class="menu2">
  <li>
    <a href="https://anton.shevchuk.name" title="Go to homepage">Home</a>
  </li>
  <li>
    <a href="https://anton.shevchuk.name/about/" title="Find out who I am">About</a>
  </li>
  <li>
    <a href="https://anton.shevchuk.name/feed/" title="Subscribe RSS feeds">Subscribe RSS</a>
  </li>
</ul>
</body>
</html>

jquery/templates/jquery/block_clickable.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Block clickable</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(function () {

      $(".pane-list li").click(function () {
        window.location = $(this).find("a").attr("href");
        return false;
      });

    }); //close doc ready
  </script>

  <style type="text/css">
    body {
      margin: 10px auto;
      width: 470px;
    }

    a {
      color: #333300;
      text-decoration: none;
    }

    a:visited {
      color: #333300;
    }

    a:hover {
      color: #333300;
      text-decoration: underline;
    }

    h3 {
      margin: 0;
      padding: 0 0 .3em;
    }

    p {
      margin: 0;
      padding: 0 0 .5em;
    }

    .pane-list {
      margin: 0;
      padding: 0;
      list-style: none;
    }

    .pane-list li {
      background: #ecfad7;
      padding: 10px 20px 10px;
      border-top: solid 1px #c4df9b;
      cursor: pointer;
    }

    .pane-list li:hover {
      background: #f6ffe9;
    }
  </style>
</head>

<body>
<ul class="pane-list">
  <li>
    <h3><a href="https://anton.shevchuk.name">Антон Шевчук</a></h3>
    <p>Блог web-разработчика</p>
  </li>
  <li>
    <h3>Online Charts Builder</h3>
    <p>Если Вы хотите быстро построить графики для вашего сайта, то этот <a href="https://charts.hohli.com">сервис</a>
      для Вас</p>
  </li>
  <li>
    <h3><a href="http://www.webdesignerwall.com">Web Designer Wall</a></h3>
    <p>A wall of design ideas, web trends, and tutorials</p>
  </li>
  <li>
    <h3>Best Web Gallery</h3>
    <p>Featuring the best <a href="http://bestwebgallery.com">CSS and Flash web sites</a></p>
  </li>
  <li>
    <h3>N.Design Studio</h3>
    <p><a href="http://www.ndesign-studio.com">Blog</a> and design portfolio of Nick La</p>
  </li>
</ul>
</body>
</html>

jquery/templates/jquery/board.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Simple Slide Panel</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(function () {

      $(".btn-slide").click(function () {
          // Данный метод добавляет или удаляет класс элемента. В первой версии, если добавляемый класс присутствует
          // у элемента то он будет удалён; если класса нет, то он будет добавлен.
        $("#panel").slideToggle("slow");
        $(this).toggleClass("active");
        return false;
      });


    });
  </script>

  <style type="text/css">
    body {
      margin: 0 auto;
      padding: 0;
      width: 570px;
      font: 75%/120% Arial, Helvetica, sans-serif;
    }

    a:focus {
      outline: none;
    }

    #panel {
      background: #754c24;
      height: 200px;
      display: none;
    }

    .slide {
      margin: 0;
      padding: 0;
      border-top: solid 4px #422410;
      background: url(../../static/images/btn-slide.gif) no-repeat center top;
    }

    .btn-slide {
      background: url(../../static/images/white-arrow.gif) no-repeat right -50px;
      text-align: center;
      width: 144px;
      height: 31px;
      padding: 10px 10px 0 0;
      margin: 0 auto;
      display: block;
      font: bold 120%/100% Arial, Helvetica, sans-serif;
      color: #fff;
      text-decoration: none;
    }

    .active {
      background-position: right 12px;
    }
  </style>
</head>

<body>

<div id="panel">
  <!-- you can put content here -->
</div>

<p class="slide"><a href="#" class="btn-slide">Slide Panel</a></p>

</body>
</html>

jquery/templates/jquery/chainable_effects.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Chainable Transition Effects</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>

  <script type="text/javascript">
    $(function () {

      $(".run").click(function () {

        $("#box").animate({opacity: "0.1", left: "+=400"}, 1200)
          .animate({opacity: "0.4", top: "+=160", height: "20", width: "20"}, "slow")
          .animate({opacity: "1", left: "0", height: "100", width: "100"}, "slow")
          .animate({top: "0"}, "fast")
          .slideUp()
          .slideDown("slow");
        return false;
      });

    });
  </script>

  <style type="text/css">
    body {
      margin: 20px auto;
      padding: 0;
      width: 580px;
      font: 80%/120% Arial, Helvetica, sans-serif;
    }

    a {
      font-weight: bold;
      color: #000000;
    }

    #box {
      background: #6699FF;
      height: 100px;
      width: 100px;
      position: relative;
    }
  </style>
</head>

<body>

<p><a href="#" class="run">Run</a></p>
<div id="box">
</div>

</body>
</html>

jquery/templates/jquery/illustrations.html
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>jQuery. Image Replacement</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
          integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
  <script type="text/javascript">
    $(function () {

      $("h2").append('<em></em>');

      $(".thumbs a").click(function () {

        var largePath = $(this).attr("href");
        var largeAlt = $(this).attr("title");

        $("#largeImg").attr({src: largePath, alt: largeAlt});

        $("h2 em").html(" (" + largeAlt + ")");
        return false;
      });

    });
  </script>

  <style type="text/css">
    body {
      margin: 20px auto;
      padding: 0;
      width: 580px;
      font: 75%/120% Arial, Helvetica, sans-serif;
    }

    h2 {
      font: bold 190%/100% Arial, Helvetica, sans-serif;
      margin: 0 0 .2em;
    }

    h2 em {
      font: normal 80%/100% Arial, Helvetica, sans-serif;
      color: #999999;
    }

    #largeImg {
      border: solid 1px #ccc;
      width: 550px;
      height: 400px;
      padding: 5px;
    }

    .thumbs img {
      border: solid 1px #ccc;
      width: 100px;
      height: 100px;
      padding: 4px;
    }

    .thumbs img:hover {
      border-color: #FF9900;
    }
  </style>
</head>

<body>

<h2>Illustrations</h2>

<p><img id="largeImg" src="../../static/images/img1-lg.jpg" alt="Large image"/></p>

<p class="thumbs">
  <a href="../../static/images/img2-lg.jpg" title="Image 2"><img src="../../static/images/img2-thumb.jpg"/></a>
  <a href="../../static/images/img3-lg.jpg" title="Image 3"><img src="../../static/images/img3-thumb.jpg"/></a>
  <a href="../../static/images/img4-lg.jpg" title="Image 4"><img src="../../static/images/img4-thumb.jpg"/></a>
  <a href="../../static/images/img5-lg.jpg" title="Image 5"><img src="../../static/images/img5-thumb.jpg"/></a>
  <a href="../../static/images/img6-lg.jpg" title="Image 6"><img src="../../static/images/img6-thumb.jpg"/></a>
</p>

</body>
</html>

jquery/templates/jquery/table.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<style type="text/css">
  .list {
      list-style: none;
  }
</style>
<div class="menu">
  <ul class="list">
    <li>
      <a href="{% url 'jquery:board' %}">Board</a>
    </li>
        <li>
      <a href="{% url 'jquery:simple_disappear' %}">Simple_disappear</a>
    </li>
        <li>
      <a href="{% url 'jquery:chainable_effects' %}">Chainable_effects</a>
    </li>
        <li>
      <a href="{% url 'jquery:accordion' %}">Accordion</a>
    </li>
        <li>
      <a href="{% url 'jquery:accordion2' %}">Accordion2</a>
    </li>
        <li>
      <a href="{% url 'jquery:animated_hover' %}">Animated hover</a>
    </li>
        <li>
      <a href="{% url 'jquery:animated_hover2' %}">Animated hover2</a>
    </li>
        <li>
      <a href="{% url 'jquery:block_clickable' %}">Block clickable</a>
    </li>
        <li>
      <a href="{% url 'jquery:collapsible_panel' %}">Collapsible panel</a>
    </li>
        <li>
      <a href="{% url 'jquery:illustrations' %}">Illustrations</a>
    </li>
  </ul>
</div>

</body>
</html>

jquery/templates/jquery/test.html
{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
     block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
       if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });
{% endblock %}